### ISSUE TITLE
Unable to successfully start XFCE 

### ISSUE THREAD

**Issue by bgatessucks** [WhitewaterFoundry/Fedora-Remix-for-WSL#29]
The desktop starts (`$ startxfce4`) with a popup window `Error: XFCE PolicyKit Agent`; after closing it the menus are responsive and I can start applications, for instance a terminal. However the keyboard does not work: I cannot type in a terminal (but I can paste with the mouse right button). 

Using:
```text
$ cat /etc/os-release
NAME=Generic
VERSION="29 (Generic)"
ID=generic
ID_LIKE=fedora
VERSION_ID=29
PRETTY_NAME="Generic 29 (Generic)"
ANSI_COLOR="0;34"
CPE_NAME="cpe:/o:generic:generic:29"
HOME_URL="http://www.zombo.com/"
SUPPORT_URL="https://en.wikipedia.org/wiki/Help!_(album)"
BUG_REPORT_URL="https://youtu.be/CSemARaqGqE"
REDHAT_BUGZILLA_PRODUCT="Generic"
REDHAT_BUGZILLA_PRODUCT_VERSION=%{bug_version}
REDHAT_SUPPORT_PRODUCT="Generic"
REDHAT_SUPPORT_PRODUCT_VERSION=%{bug_version}
PRIVACY_POLICY_URL="http://nsa.gov"
```

with `VcXsvr` X Server version ``1.20.1.4.

```text
$ startxfce4
/usr/bin/startxfce4: X server already running on display :0.0
_IceTransmkdir: Owner of /tmp/.ICE-unix should be set to root
gpg-agent[3608]: WARNING: "--write-env-file" is an obsolete option - it has no effect
gpg-agent: a gpg-agent is already running - not starting a new one

(xfce4-session:3591): xfce4-session-WARNING **: 08:22:56.700: gpg-agent returned no PID in the variables

(xfsettingsd:3622): xfsettingsd-WARNING **: 08:22:58.451: Property "/Gdk/WindowScalingFactor" has an unsupported type "guint".

(xfsettingsd:3622): xfsettingsd-CRITICAL **: 08:22:58.474: Failed to apply display settings

(xfce4-session:3591): xfce4-session-WARNING **: 08:22:59.352: Unable to launch "/usr/bin/python2 /usr/lib/blueberry/blueberry-tray.py": Failed to execute child process “/usr/bin/python2 /usr/lib/blueberry/blueberry-tray.py” (No such file or directory)

(wrapper-2.0:3635): Gtk-WARNING **: 08:22:59.558: gtk_widget_size_allocate(): attempt to allocate widget with width -1 and height 28

(wrapper-2.0:3635): Gtk-WARNING **: 08:22:59.559: Negative content width -1 (allocation 1, extents 1x1) while allocating gadget (node border, owner GtkFrame)

** (agent:3663): CRITICAL **: 08:22:59.654: Failed to get connection to system bus: Could not connect: No such file or directory
vmware-user: could not open /proc/fs/vmblock/dev

(xfdesktop:3629): GVFS-RemoteVolumeMonitor-WARNING **: 08:23:00.108: remote volume monitor with dbus name org.gtk.vfs.UDisks2VolumeMonitor is not supported

** (xfce-polkit:3731): CRITICAL **: 08:23:00.288: polkit_agent_listener_register_with_options: assertion 'POLKIT_IS_SUBJECT (subject)' failed

(nm-applet:3675): nm-applet-WARNING **: 08:23:00.369: Error connecting to system D-Bus: Could not connect: No such file or directory

(nm-applet:3675): nm-applet-WARNING **: 08:23:00.373: Could not connect: No such file or directory

(nm-applet:3675): libnm-CRITICAL **: 08:23:00.426: ((libnm/nm-client.c:268)): assertion '<dropped>' failed

(nm-applet:3675): libnm-CRITICAL **: 08:23:00.427: ((libnm/nm-client.c:229)): assertion '<dropped>' failed
abrt-applet: Can't connect to system dbus: Could not connect: No such file or directory: No such file or directory

(nm-applet:3675): libnm-CRITICAL **: 08:23:00.505: ((libnm/nm-client.c:986)): assertion '<dropped>' failed

(xfce4-session:3591): xfce4-session-WARNING **: 08:23:00.515: failed to run script: Failed to execute child process “/usr/bin/pm-is-supported” (No such file or directory)

(xfce4-session:3591): xfce4-session-WARNING **: 08:23:00.554: failed to run script: Failed to execute child process “/usr/bin/pm-is-supported” (No such file or directory)

(xfce4-session:3591): xfce4-session-WARNING **: 08:23:00.590: failed to run script: Failed to execute child process “/usr/bin/pm-is-supported” (No such file or directory)
Traceback (most recent call last):
  File "/usr/bin/dnfdragora-updater", line 32, in <module>
    import dnfdaemon.client
  File "/usr/lib/python3.7/site-packages/dnfdaemon/client/__init__.py", line 191, in <module>
    system = DBus(Gio.bus_get_sync(Gio.BusType.SYSTEM, None))
gi.repository.GLib.Error: g-io-error-quark: Could not connect: No such file or directory (1)

(wrapper-2.0:3639): Gtk-WARNING **: 08:23:00.742: Negative content width -1 (allocation 1, extents 1x1) while allocating gadget (node button, owner XfceArrowButton)
shared memfd open() failed: Function not implemented
shared memfd open() failed: Function not implemented
shared memfd open() failed: Function not implemented
SELinux Troubleshooter: Applet requires SELinux be enabled to run
rfkill: cannot open /dev/rfkill: No such file or directory
rfkill: cannot read /dev/rfkill: Bad file descriptor
Traceback (most recent call last):
  File "/usr/lib/blueberry/blueberry-tray.py", line 29, in do_startup
    self.rfkill = rfkillMagic.Interface(self.update_icon_callback, debug)
  File "/usr/lib/blueberry/rfkillMagic.py", line 29, in __init__
    self.have_adapter = self.adapter_check()
  File "/usr/lib/blueberry/rfkillMagic.py", line 35, in adapter_check
    res = subprocess.check_output(RFKILL_CHK)
  File "/usr/lib64/python2.7/subprocess.py", line 223, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['/usr/sbin/rfkill', 'list', 'bluetooth']' returned non-zero exit status 1

(xfce4-terminal:3636): IBUS-WARNING **: 08:23:03.322: Unable to connect to ibus: Unexpected lack of content trying to read a line
xscreensaver: 08:23:10: no keyboard or mouse data in /proc/interrupts?
```

**Comment by sirredbeard** [comment]
Which X server are you using?

**Comment by bgatessucks** [comment]
As said above, `VcXsvr` X Server version `1.20.1.4` from [sourceforge](https://sourceforge.net/projects/vcxsrv/).

**Comment by PTrenholme** [comment]
I've been running with no (significant) problems using the X410 display window. Here's a log of the startxfce4 console output.

Of possible interest, I installed the KDE Desktop group, but plasmashell won't start, However the striping of the ABI section from libQt5Core.so (suggested in the Ubuntu blog) allows (the ones I use) of the KDE Qt5 applications to run in the Xfce desktop.

[startxfce4.log](https://github.com/WhitewaterFoundry/Fedora-Remix-for-WSL/files/3014972/startxfce4.log)

**Comment by WSLUser** [comment]
`xfce4-session` always works even if `startxfce4` doesn't. There is known issue with KDE on WSL. There's an issue tracker for it that has some solutions that may be able to be applied to Fedora (haven't had a chance to test) but one of those required options is the removal of the `libQt5Core.so`.

**Comment by Biswa96** [comment]
I have installed and run XFCE4 in Fedora 30 ([details here](https://github.com/Biswa96/WSLInstall/blob/master/docs/Install_Desktop_Environments.md)). No extra steps are required. 

BTW, every Windows Store package from WhitewaterFoundry contains `/etc/resolv.conf` with random DNS IPs. Maybe developers should remove `/etc/resolv.conf` file before packaging. Otherwise LxssManager does not automatically sync DNS from Windows side.

**Comment by Biswa96** [comment]
> However the keyboard does not work: I cannot type in a terminal (but I can paste with the mouse right button).

Try this `export GTK_IM_MODULE=xim`

Source: https://bugs.launchpad.net/ubuntu/+source/ibus/+bug/1421483

**Comment by bgatessucks** [comment]
The suggestion [here](https://github.com/WhitewaterFoundry/Pengwin/issues/238#issuecomment-466675937) works and it solves my problem. I can start and use XFCE.
